import type { ShootingSourceSeedRow } from "@/lib/shootingIngestion/types";

export const sourceSeedDefaults: ShootingSourceSeedRow[] = [
  {
    sourceId: "mssz-home",
    sourceClass: "federation",
    operatorName: "MSSZ",
    operatorType: "association",
    canonicalUrl: "https://www.mssz.hu/",
    discoveryUrls: ["https://www.mssz.hu/versenyek/", "https://www.mssz.hu/versenynaptar/"],
    trustTier: "official_primary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["IPSC", "pistol", "rifle", "shotgun"],
    geoHints: ["HU"],
    freshnessSlaHours: 12,
    countryCode: "HU",
    sourceNotes: "Primary national federation surface for official competition notices and rules.",
  },
  {
    sourceId: "mssz-match-calendar",
    sourceClass: "competition_surface",
    operatorName: "MSSZ",
    operatorType: "association",
    canonicalUrl: "https://www.mssz.hu/versenyek/",
    discoveryUrls: ["https://www.mssz.hu/versenyek/", "https://www.mssz.hu/versenynaptar/"],
    trustTier: "official_primary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["practical-shooting", "dynamic", "IDPA-like"],
    geoHints: ["HU"],
    freshnessSlaHours: 6,
    countryCode: "HU",
    sourceNotes: "Primary official competition calendar feed candidate.",
  },
  {
    sourceId: "mdlsz-home",
    sourceClass: "federation",
    operatorName: "MDLSZ",
    operatorType: "association",
    canonicalUrl: "https://www.mdlsz.hu/",
    discoveryUrls: ["https://www.mdlsz.hu/versenyek/", "https://www.mdlsz.hu/tudnivalok/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["hunter", "shotgun", "rifle"],
    geoHints: ["HU"],
    freshnessSlaHours: 12,
    countryCode: "HU",
    sourceNotes: "Hunting federation surface for non-match hunting events and notices.",
  },
  {
    sourceId: "mdlsz-events",
    sourceClass: "competition_surface",
    operatorName: "MDLSZ",
    operatorType: "association",
    canonicalUrl: "https://www.mdlsz.hu/versenyek/",
    discoveryUrls: ["https://www.mdlsz.hu/versenyek/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["field-shoot", "clays"],
    geoHints: ["HU"],
    freshnessSlaHours: 12,
    countryCode: "HU",
    sourceNotes: "Hunting competitions and event calendar.",
  },
  {
    sourceId: "ipsc-hu-home",
    sourceClass: "federation",
    operatorName: "IPSC Hungary",
    operatorType: "association",
    canonicalUrl: "https://www.ipschungary.hu/",
    discoveryUrls: ["https://www.ipschungary.hu/", "https://www.ipschungary.hu/versenyek/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["IPSC", "action", "practical"],
    geoHints: ["HU"],
    freshnessSlaHours: 12,
    countryCode: "HU",
    sourceNotes: "Discipline federation with practical shooting competition pages.",
  },
  {
    sourceId: "idpa-hu-home",
    sourceClass: "federation",
    operatorName: "IDPA Hungary",
    operatorType: "association",
    canonicalUrl: "https://www.idpa-hungary.org/",
    discoveryUrls: ["https://www.idpa-hungary.org/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["IDPA", "defensive"],
    geoHints: ["HU"],
    freshnessSlaHours: 24,
    countryCode: "HU",
    sourceNotes: "Discipline federation seed.",
  },
  {
    sourceId: "practiscore-hungary-portal",
    sourceClass: "registration_surface",
    operatorName: "PractiScore Hungary users",
    operatorType: "unknown",
    canonicalUrl: "https://practiscore.com/",
    discoveryUrls: ["https://practiscore.com/login/", "https://practiscore.com/calendar/"],
    trustTier: "official_primary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: true,
    disciplineHints: ["all"],
    geoHints: ["HU", "EU"],
    freshnessSlaHours: 2,
    countryCode: "HU",
    sourceNotes: "PractiScore is required for registration readiness checks and scorebook flow.",
  },
  {
    sourceId: "club-directory-hu",
    sourceClass: "club_surface",
    operatorName: "Client curated club directory",
    operatorType: "club",
    canonicalUrl: "https://www.mssz.hu/tagok/",
    discoveryUrls: ["https://www.mssz.hu/tagok/", "https://www.mdlsz.hu/tagok/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["shotgun", "rifle", "pistol", "pigeon", "trap", "skeet"],
    geoHints: ["HU"],
    freshnessSlaHours: 72,
    countryCode: "HU",
    sourceNotes: "Fallback club directory sources from known federation surfaces.",
  },
  {
    sourceId: "range-directory-hu",
    sourceClass: "range_surface",
    operatorName: "Range capability index (seed)",
    operatorType: "range",
    canonicalUrl: "https://www.hunfirearms.hu/",
    discoveryUrls: ["https://www.hunfirearms.hu/termekeink/", "https://www.hunfirearms.hu/kapcsolat/"],
    trustTier: "community_hint",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["equipment", "training-range", "ammo-range"],
    geoHints: ["HU"],
    freshnessSlaHours: 168,
    countryCode: "HU",
    sourceNotes: "Community-recommended seed for range/equipment context until verified directories arrive.",
  },
  {
    sourceId: "course-directory-hu",
    sourceClass: "course_surface",
    operatorName: "Client course seed index",
    operatorType: "trainer",
    canonicalUrl: "https://www.mssz.hu/versenyelesi-kepzes/",
    discoveryUrls: ["https://www.mssz.hu/versenyelesi-kepzes/"],
    trustTier: "official_secondary",
    fetchPolicy: "html",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["beginner", "training-course", "competition-prep"],
    geoHints: ["HU"],
    freshnessSlaHours: 72,
    countryCode: "HU",
    sourceNotes: "Trainer/course page seed for beginner onboarding rules.",
  },
  {
    sourceId: "local-rules-manual",
    sourceClass: "document_surface",
    operatorName: "Client Documents",
    operatorType: "association",
    canonicalUrl: "https://www.mssz.hu/letoltesek/",
    discoveryUrls: ["https://www.mssz.hu/letoltesek/"],
    trustTier: "official_secondary",
    fetchPolicy: "pdf",
    robotsStatus: "unknown",
    requiresAuth: false,
    disciplineHints: ["all"],
    geoHints: ["HU"],
    freshnessSlaHours: 168,
    countryCode: "HU",
    sourceNotes: "PDF and document surface for regulation extraction and evidence links.",
  },
];
